2025-07-18 23:53:54,018 -  nornir.core -     INFO -        run() - Running task "Execute 'show ip interface brief' and parse with Genie" with args {'command_to_run': 'show ip interface brief'} on 3 hosts
2025-07-18 23:53:54,028 - nornir.core.task -    ERROR -      start() - Host 'leaf1': task 'netmiko_send_command' failed with traceback:
Traceback (most recent call last):
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/nornir_netmiko/tasks/netmiko_send_command.py", line 26, in netmiko_send_command
    net_connect = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/nornir/core/inventory.py", line 476, in get_connection
    self.open_connection(
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/nornir/core/inventory.py", line 528, in open_connection
    conn_obj.open(
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/nornir_netmiko/connections/netmiko.py", line 59, in open
    connection = ConnectHandler(**parameters)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/netmiko/ssh_dispatcher.py", line 455, in ConnectHandler
    raise ValueError(
ValueError: Unsupported 'device_type' currently supported platforms are:
a10
accedian
adtran_os
adva_fsp150f2
adva_fsp150f3
alaxala_ax26s
alaxala_ax36s
alcatel_aos
alcatel_sros
allied_telesis_awplus
apresia_aeos
arista_eos
arris_cer
aruba_aoscx
aruba_os
aruba_osswitch
aruba_procurve
asterfusion_asternos
audiocode_66
audiocode_72
audiocode_shell
avaya_ers
avaya_vsp
bintec_boss
broadcom_icos
brocade_fastiron
brocade_fos
brocade_netiron
brocade_nos
brocade_vdx
brocade_vyos
calix_b6
casa_cmts
cdot_cros
centec_os
checkpoint_gaia
ciena_saos
ciena_saos10
ciena_waveserver
cisco_apic
cisco_asa
cisco_ftd
cisco_ios
cisco_nxos
cisco_s200
cisco_s300
cisco_tp
cisco_viptela
cisco_wlc
cisco_xe
cisco_xr
cloudgenix_ion
corelight_linux
coriant
cumulus_linux
dell_dnos9
dell_force10
dell_isilon
dell_os10
dell_os6
dell_os9
dell_powerconnect
dell_sonic
digi_transport
dlink_ds
edgecore_sonic
ekinops_ek360
eltex
eltex_esr
endace
enterasys
ericsson_ipos
ericsson_mltn63
ericsson_mltn66
extreme
extreme_ers
extreme_exos
extreme_netiron
extreme_nos
extreme_slx
extreme_tierra
extreme_vdx
extreme_vsp
extreme_wing
f5_linux
f5_ltm
f5_tmsh
fiberstore_fsos
fiberstore_fsosv2
fiberstore_networkos
flexvnf
fortinet
garderos_grs
generic
generic_termserver
h3c_comware
hillstone_stoneos
hp_comware
hp_procurve
huawei
huawei_olt
huawei_smartax
huawei_smartaxmmi
huawei_vrp
huawei_vrpv8
infinera_packet
ipinfusion_ocnos
juniper
juniper_junos
juniper_screenos
keymile
keymile_nos
lancom_lcossx4
linux
maipu
mellanox
mellanox_mlnxos
mikrotik_routeros
mikrotik_switchos
mrv_lx
mrv_optiswitch
nec_ix
netapp_cdot
netgear_prosafe
netscaler
nokia_srl
nokia_sros
oneaccess_oneos
ovs_linux
paloalto_panos
pluribus
quanta_mesh
rad_etx
raisecom_roap
ruckus_fastiron
ruijie_os
silverpeak_vxoa
sixwind_os
sophos_sfos
supermicro_smis
telcosystems_binos
teldat_cit
tplink_jetstream
ubiquiti_edge
ubiquiti_edgerouter
ubiquiti_edgeswitch
ubiquiti_unifiswitch
vertiv_mph
vyatta_vyos
vyos
watchguard_fireware
yamaha
zte_zxros
zyxel_os

2025-07-18 23:53:54,028 - nornir.core.task -    ERROR -      start() - Host 'leaf2': task 'netmiko_send_command' failed with traceback:
Traceback (most recent call last):
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/nornir_netmiko/tasks/netmiko_send_command.py", line 26, in netmiko_send_command
    net_connect = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/nornir/core/inventory.py", line 476, in get_connection
    self.open_connection(
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/nornir/core/inventory.py", line 528, in open_connection
    conn_obj.open(
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/nornir_netmiko/connections/netmiko.py", line 59, in open
    connection = ConnectHandler(**parameters)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/netmiko/ssh_dispatcher.py", line 455, in ConnectHandler
    raise ValueError(
ValueError: Unsupported 'device_type' currently supported platforms are:
a10
accedian
adtran_os
adva_fsp150f2
adva_fsp150f3
alaxala_ax26s
alaxala_ax36s
alcatel_aos
alcatel_sros
allied_telesis_awplus
apresia_aeos
arista_eos
arris_cer
aruba_aoscx
aruba_os
aruba_osswitch
aruba_procurve
asterfusion_asternos
audiocode_66
audiocode_72
audiocode_shell
avaya_ers
avaya_vsp
bintec_boss
broadcom_icos
brocade_fastiron
brocade_fos
brocade_netiron
brocade_nos
brocade_vdx
brocade_vyos
calix_b6
casa_cmts
cdot_cros
centec_os
checkpoint_gaia
ciena_saos
ciena_saos10
ciena_waveserver
cisco_apic
cisco_asa
cisco_ftd
cisco_ios
cisco_nxos
cisco_s200
cisco_s300
cisco_tp
cisco_viptela
cisco_wlc
cisco_xe
cisco_xr
cloudgenix_ion
corelight_linux
coriant
cumulus_linux
dell_dnos9
dell_force10
dell_isilon
dell_os10
dell_os6
dell_os9
dell_powerconnect
dell_sonic
digi_transport
dlink_ds
edgecore_sonic
ekinops_ek360
eltex
eltex_esr
endace
enterasys
ericsson_ipos
ericsson_mltn63
ericsson_mltn66
extreme
extreme_ers
extreme_exos
extreme_netiron
extreme_nos
extreme_slx
extreme_tierra
extreme_vdx
extreme_vsp
extreme_wing
f5_linux
f5_ltm
f5_tmsh
fiberstore_fsos
fiberstore_fsosv2
fiberstore_networkos
flexvnf
fortinet
garderos_grs
generic
generic_termserver
h3c_comware
hillstone_stoneos
hp_comware
hp_procurve
huawei
huawei_olt
huawei_smartax
huawei_smartaxmmi
huawei_vrp
huawei_vrpv8
infinera_packet
ipinfusion_ocnos
juniper
juniper_junos
juniper_screenos
keymile
keymile_nos
lancom_lcossx4
linux
maipu
mellanox
mellanox_mlnxos
mikrotik_routeros
mikrotik_switchos
mrv_lx
mrv_optiswitch
nec_ix
netapp_cdot
netgear_prosafe
netscaler
nokia_srl
nokia_sros
oneaccess_oneos
ovs_linux
paloalto_panos
pluribus
quanta_mesh
rad_etx
raisecom_roap
ruckus_fastiron
ruijie_os
silverpeak_vxoa
sixwind_os
sophos_sfos
supermicro_smis
telcosystems_binos
teldat_cit
tplink_jetstream
ubiquiti_edge
ubiquiti_edgerouter
ubiquiti_edgeswitch
ubiquiti_unifiswitch
vertiv_mph
vyatta_vyos
vyos
watchguard_fireware
yamaha
zte_zxros
zyxel_os

2025-07-18 23:53:54,028 - nornir.core.task -    ERROR -      start() - Host 'spine1': task 'netmiko_send_command' failed with traceback:
Traceback (most recent call last):
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/nornir_netmiko/tasks/netmiko_send_command.py", line 26, in netmiko_send_command
    net_connect = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/nornir/core/inventory.py", line 476, in get_connection
    self.open_connection(
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/nornir/core/inventory.py", line 528, in open_connection
    conn_obj.open(
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/nornir_netmiko/connections/netmiko.py", line 59, in open
    connection = ConnectHandler(**parameters)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/netmiko/ssh_dispatcher.py", line 455, in ConnectHandler
    raise ValueError(
ValueError: Unsupported 'device_type' currently supported platforms are:
a10
accedian
adtran_os
adva_fsp150f2
adva_fsp150f3
alaxala_ax26s
alaxala_ax36s
alcatel_aos
alcatel_sros
allied_telesis_awplus
apresia_aeos
arista_eos
arris_cer
aruba_aoscx
aruba_os
aruba_osswitch
aruba_procurve
asterfusion_asternos
audiocode_66
audiocode_72
audiocode_shell
avaya_ers
avaya_vsp
bintec_boss
broadcom_icos
brocade_fastiron
brocade_fos
brocade_netiron
brocade_nos
brocade_vdx
brocade_vyos
calix_b6
casa_cmts
cdot_cros
centec_os
checkpoint_gaia
ciena_saos
ciena_saos10
ciena_waveserver
cisco_apic
cisco_asa
cisco_ftd
cisco_ios
cisco_nxos
cisco_s200
cisco_s300
cisco_tp
cisco_viptela
cisco_wlc
cisco_xe
cisco_xr
cloudgenix_ion
corelight_linux
coriant
cumulus_linux
dell_dnos9
dell_force10
dell_isilon
dell_os10
dell_os6
dell_os9
dell_powerconnect
dell_sonic
digi_transport
dlink_ds
edgecore_sonic
ekinops_ek360
eltex
eltex_esr
endace
enterasys
ericsson_ipos
ericsson_mltn63
ericsson_mltn66
extreme
extreme_ers
extreme_exos
extreme_netiron
extreme_nos
extreme_slx
extreme_tierra
extreme_vdx
extreme_vsp
extreme_wing
f5_linux
f5_ltm
f5_tmsh
fiberstore_fsos
fiberstore_fsosv2
fiberstore_networkos
flexvnf
fortinet
garderos_grs
generic
generic_termserver
h3c_comware
hillstone_stoneos
hp_comware
hp_procurve
huawei
huawei_olt
huawei_smartax
huawei_smartaxmmi
huawei_vrp
huawei_vrpv8
infinera_packet
ipinfusion_ocnos
juniper
juniper_junos
juniper_screenos
keymile
keymile_nos
lancom_lcossx4
linux
maipu
mellanox
mellanox_mlnxos
mikrotik_routeros
mikrotik_switchos
mrv_lx
mrv_optiswitch
nec_ix
netapp_cdot
netgear_prosafe
netscaler
nokia_srl
nokia_sros
oneaccess_oneos
ovs_linux
paloalto_panos
pluribus
quanta_mesh
rad_etx
raisecom_roap
ruckus_fastiron
ruijie_os
silverpeak_vxoa
sixwind_os
sophos_sfos
supermicro_smis
telcosystems_binos
teldat_cit
tplink_jetstream
ubiquiti_edge
ubiquiti_edgerouter
ubiquiti_edgeswitch
ubiquiti_unifiswitch
vertiv_mph
vyatta_vyos
vyos
watchguard_fireware
yamaha
zte_zxros
zyxel_os

2025-07-19 00:05:45,928 -  nornir.core -     INFO -        run() - Running task "Execute 'show ip interface brief' and parse with Genie" with args {'command_to_run': 'show ip interface brief'} on 3 hosts
2025-07-19 00:05:45,938 - nornir.core.task -    ERROR -      start() - Host 'leaf1': task 'netmiko_send_command' failed with traceback:
Traceback (most recent call last):
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/nornir_netmiko/tasks/netmiko_send_command.py", line 26, in netmiko_send_command
    net_connect = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/nornir/core/inventory.py", line 476, in get_connection
    self.open_connection(
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/nornir/core/inventory.py", line 528, in open_connection
    conn_obj.open(
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/nornir_netmiko/connections/netmiko.py", line 59, in open
    connection = ConnectHandler(**parameters)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/netmiko/ssh_dispatcher.py", line 455, in ConnectHandler
    raise ValueError(
ValueError: Unsupported 'device_type' currently supported platforms are:
a10
accedian
adtran_os
adva_fsp150f2
adva_fsp150f3
alaxala_ax26s
alaxala_ax36s
alcatel_aos
alcatel_sros
allied_telesis_awplus
apresia_aeos
arista_eos
arris_cer
aruba_aoscx
aruba_os
aruba_osswitch
aruba_procurve
asterfusion_asternos
audiocode_66
audiocode_72
audiocode_shell
avaya_ers
avaya_vsp
bintec_boss
broadcom_icos
brocade_fastiron
brocade_fos
brocade_netiron
brocade_nos
brocade_vdx
brocade_vyos
calix_b6
casa_cmts
cdot_cros
centec_os
checkpoint_gaia
ciena_saos
ciena_saos10
ciena_waveserver
cisco_apic
cisco_asa
cisco_ftd
cisco_ios
cisco_nxos
cisco_s200
cisco_s300
cisco_tp
cisco_viptela
cisco_wlc
cisco_xe
cisco_xr
cloudgenix_ion
corelight_linux
coriant
cumulus_linux
dell_dnos9
dell_force10
dell_isilon
dell_os10
dell_os6
dell_os9
dell_powerconnect
dell_sonic
digi_transport
dlink_ds
edgecore_sonic
ekinops_ek360
eltex
eltex_esr
endace
enterasys
ericsson_ipos
ericsson_mltn63
ericsson_mltn66
extreme
extreme_ers
extreme_exos
extreme_netiron
extreme_nos
extreme_slx
extreme_tierra
extreme_vdx
extreme_vsp
extreme_wing
f5_linux
f5_ltm
f5_tmsh
fiberstore_fsos
fiberstore_fsosv2
fiberstore_networkos
flexvnf
fortinet
garderos_grs
generic
generic_termserver
h3c_comware
hillstone_stoneos
hp_comware
hp_procurve
huawei
huawei_olt
huawei_smartax
huawei_smartaxmmi
huawei_vrp
huawei_vrpv8
infinera_packet
ipinfusion_ocnos
juniper
juniper_junos
juniper_screenos
keymile
keymile_nos
lancom_lcossx4
linux
maipu
mellanox
mellanox_mlnxos
mikrotik_routeros
mikrotik_switchos
mrv_lx
mrv_optiswitch
nec_ix
netapp_cdot
netgear_prosafe
netscaler
nokia_srl
nokia_sros
oneaccess_oneos
ovs_linux
paloalto_panos
pluribus
quanta_mesh
rad_etx
raisecom_roap
ruckus_fastiron
ruijie_os
silverpeak_vxoa
sixwind_os
sophos_sfos
supermicro_smis
telcosystems_binos
teldat_cit
tplink_jetstream
ubiquiti_edge
ubiquiti_edgerouter
ubiquiti_edgeswitch
ubiquiti_unifiswitch
vertiv_mph
vyatta_vyos
vyos
watchguard_fireware
yamaha
zte_zxros
zyxel_os

2025-07-19 00:05:45,938 - nornir.core.task -    ERROR -      start() - Host 'spine1': task 'netmiko_send_command' failed with traceback:
Traceback (most recent call last):
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/nornir_netmiko/tasks/netmiko_send_command.py", line 26, in netmiko_send_command
    net_connect = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/nornir/core/inventory.py", line 476, in get_connection
    self.open_connection(
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/nornir/core/inventory.py", line 528, in open_connection
    conn_obj.open(
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/nornir_netmiko/connections/netmiko.py", line 59, in open
    connection = ConnectHandler(**parameters)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/netmiko/ssh_dispatcher.py", line 455, in ConnectHandler
    raise ValueError(
ValueError: Unsupported 'device_type' currently supported platforms are:
a10
accedian
adtran_os
adva_fsp150f2
adva_fsp150f3
alaxala_ax26s
alaxala_ax36s
alcatel_aos
alcatel_sros
allied_telesis_awplus
apresia_aeos
arista_eos
arris_cer
aruba_aoscx
aruba_os
aruba_osswitch
aruba_procurve
asterfusion_asternos
audiocode_66
audiocode_72
audiocode_shell
avaya_ers
avaya_vsp
bintec_boss
broadcom_icos
brocade_fastiron
brocade_fos
brocade_netiron
brocade_nos
brocade_vdx
brocade_vyos
calix_b6
casa_cmts
cdot_cros
centec_os
checkpoint_gaia
ciena_saos
ciena_saos10
ciena_waveserver
cisco_apic
cisco_asa
cisco_ftd
cisco_ios
cisco_nxos
cisco_s200
cisco_s300
cisco_tp
cisco_viptela
cisco_wlc
cisco_xe
cisco_xr
cloudgenix_ion
corelight_linux
coriant
cumulus_linux
dell_dnos9
dell_force10
dell_isilon
dell_os10
dell_os6
dell_os9
dell_powerconnect
dell_sonic
digi_transport
dlink_ds
edgecore_sonic
ekinops_ek360
eltex
eltex_esr
endace
enterasys
ericsson_ipos
ericsson_mltn63
ericsson_mltn66
extreme
extreme_ers
extreme_exos
extreme_netiron
extreme_nos
extreme_slx
extreme_tierra
extreme_vdx
extreme_vsp
extreme_wing
f5_linux
f5_ltm
f5_tmsh
fiberstore_fsos
fiberstore_fsosv2
fiberstore_networkos
flexvnf
fortinet
garderos_grs
generic
generic_termserver
h3c_comware
hillstone_stoneos
hp_comware
hp_procurve
huawei
huawei_olt
huawei_smartax
huawei_smartaxmmi
huawei_vrp
huawei_vrpv8
infinera_packet
ipinfusion_ocnos
juniper
juniper_junos
juniper_screenos
keymile
keymile_nos
lancom_lcossx4
linux
maipu
mellanox
mellanox_mlnxos
mikrotik_routeros
mikrotik_switchos
mrv_lx
mrv_optiswitch
nec_ix
netapp_cdot
netgear_prosafe
netscaler
nokia_srl
nokia_sros
oneaccess_oneos
ovs_linux
paloalto_panos
pluribus
quanta_mesh
rad_etx
raisecom_roap
ruckus_fastiron
ruijie_os
silverpeak_vxoa
sixwind_os
sophos_sfos
supermicro_smis
telcosystems_binos
teldat_cit
tplink_jetstream
ubiquiti_edge
ubiquiti_edgerouter
ubiquiti_edgeswitch
ubiquiti_unifiswitch
vertiv_mph
vyatta_vyos
vyos
watchguard_fireware
yamaha
zte_zxros
zyxel_os

2025-07-19 00:05:45,938 - nornir.core.task -    ERROR -      start() - Host 'leaf2': task 'netmiko_send_command' failed with traceback:
Traceback (most recent call last):
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/nornir_netmiko/tasks/netmiko_send_command.py", line 26, in netmiko_send_command
    net_connect = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/nornir/core/inventory.py", line 476, in get_connection
    self.open_connection(
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/nornir/core/inventory.py", line 528, in open_connection
    conn_obj.open(
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/nornir_netmiko/connections/netmiko.py", line 59, in open
    connection = ConnectHandler(**parameters)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/netmiko/ssh_dispatcher.py", line 455, in ConnectHandler
    raise ValueError(
ValueError: Unsupported 'device_type' currently supported platforms are:
a10
accedian
adtran_os
adva_fsp150f2
adva_fsp150f3
alaxala_ax26s
alaxala_ax36s
alcatel_aos
alcatel_sros
allied_telesis_awplus
apresia_aeos
arista_eos
arris_cer
aruba_aoscx
aruba_os
aruba_osswitch
aruba_procurve
asterfusion_asternos
audiocode_66
audiocode_72
audiocode_shell
avaya_ers
avaya_vsp
bintec_boss
broadcom_icos
brocade_fastiron
brocade_fos
brocade_netiron
brocade_nos
brocade_vdx
brocade_vyos
calix_b6
casa_cmts
cdot_cros
centec_os
checkpoint_gaia
ciena_saos
ciena_saos10
ciena_waveserver
cisco_apic
cisco_asa
cisco_ftd
cisco_ios
cisco_nxos
cisco_s200
cisco_s300
cisco_tp
cisco_viptela
cisco_wlc
cisco_xe
cisco_xr
cloudgenix_ion
corelight_linux
coriant
cumulus_linux
dell_dnos9
dell_force10
dell_isilon
dell_os10
dell_os6
dell_os9
dell_powerconnect
dell_sonic
digi_transport
dlink_ds
edgecore_sonic
ekinops_ek360
eltex
eltex_esr
endace
enterasys
ericsson_ipos
ericsson_mltn63
ericsson_mltn66
extreme
extreme_ers
extreme_exos
extreme_netiron
extreme_nos
extreme_slx
extreme_tierra
extreme_vdx
extreme_vsp
extreme_wing
f5_linux
f5_ltm
f5_tmsh
fiberstore_fsos
fiberstore_fsosv2
fiberstore_networkos
flexvnf
fortinet
garderos_grs
generic
generic_termserver
h3c_comware
hillstone_stoneos
hp_comware
hp_procurve
huawei
huawei_olt
huawei_smartax
huawei_smartaxmmi
huawei_vrp
huawei_vrpv8
infinera_packet
ipinfusion_ocnos
juniper
juniper_junos
juniper_screenos
keymile
keymile_nos
lancom_lcossx4
linux
maipu
mellanox
mellanox_mlnxos
mikrotik_routeros
mikrotik_switchos
mrv_lx
mrv_optiswitch
nec_ix
netapp_cdot
netgear_prosafe
netscaler
nokia_srl
nokia_sros
oneaccess_oneos
ovs_linux
paloalto_panos
pluribus
quanta_mesh
rad_etx
raisecom_roap
ruckus_fastiron
ruijie_os
silverpeak_vxoa
sixwind_os
sophos_sfos
supermicro_smis
telcosystems_binos
teldat_cit
tplink_jetstream
ubiquiti_edge
ubiquiti_edgerouter
ubiquiti_edgeswitch
ubiquiti_unifiswitch
vertiv_mph
vyatta_vyos
vyos
watchguard_fireware
yamaha
zte_zxros
zyxel_os

2025-07-19 00:09:19,587 -  nornir.core -     INFO -        run() - Running task "Execute 'show ip interface brief' and parse with Genie" with args {'command_to_run': 'show ip interface brief'} on 3 hosts
2025-07-19 00:09:19,591 - nornir.core.task -    ERROR -      start() - Host 'leaf1': task 'netmiko_send_command' failed with traceback:
Traceback (most recent call last):
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/nornir_netmiko/tasks/netmiko_send_command.py", line 26, in netmiko_send_command
    net_connect = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/nornir/core/inventory.py", line 476, in get_connection
    self.open_connection(
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/nornir/core/inventory.py", line 528, in open_connection
    conn_obj.open(
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/nornir_netmiko/connections/netmiko.py", line 59, in open
    connection = ConnectHandler(**parameters)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/netmiko/ssh_dispatcher.py", line 455, in ConnectHandler
    raise ValueError(
ValueError: Unsupported 'device_type' currently supported platforms are:
a10
accedian
adtran_os
adva_fsp150f2
adva_fsp150f3
alaxala_ax26s
alaxala_ax36s
alcatel_aos
alcatel_sros
allied_telesis_awplus
apresia_aeos
arista_eos
arris_cer
aruba_aoscx
aruba_os
aruba_osswitch
aruba_procurve
asterfusion_asternos
audiocode_66
audiocode_72
audiocode_shell
avaya_ers
avaya_vsp
bintec_boss
broadcom_icos
brocade_fastiron
brocade_fos
brocade_netiron
brocade_nos
brocade_vdx
brocade_vyos
calix_b6
casa_cmts
cdot_cros
centec_os
checkpoint_gaia
ciena_saos
ciena_saos10
ciena_waveserver
cisco_apic
cisco_asa
cisco_ftd
cisco_ios
cisco_nxos
cisco_s200
cisco_s300
cisco_tp
cisco_viptela
cisco_wlc
cisco_xe
cisco_xr
cloudgenix_ion
corelight_linux
coriant
cumulus_linux
dell_dnos9
dell_force10
dell_isilon
dell_os10
dell_os6
dell_os9
dell_powerconnect
dell_sonic
digi_transport
dlink_ds
edgecore_sonic
ekinops_ek360
eltex
eltex_esr
endace
enterasys
ericsson_ipos
ericsson_mltn63
ericsson_mltn66
extreme
extreme_ers
extreme_exos
extreme_netiron
extreme_nos
extreme_slx
extreme_tierra
extreme_vdx
extreme_vsp
extreme_wing
f5_linux
f5_ltm
f5_tmsh
fiberstore_fsos
fiberstore_fsosv2
fiberstore_networkos
flexvnf
fortinet
garderos_grs
generic
generic_termserver
h3c_comware
hillstone_stoneos
hp_comware
hp_procurve
huawei
huawei_olt
huawei_smartax
huawei_smartaxmmi
huawei_vrp
huawei_vrpv8
infinera_packet
ipinfusion_ocnos
juniper
juniper_junos
juniper_screenos
keymile
keymile_nos
lancom_lcossx4
linux
maipu
mellanox
mellanox_mlnxos
mikrotik_routeros
mikrotik_switchos
mrv_lx
mrv_optiswitch
nec_ix
netapp_cdot
netgear_prosafe
netscaler
nokia_srl
nokia_sros
oneaccess_oneos
ovs_linux
paloalto_panos
pluribus
quanta_mesh
rad_etx
raisecom_roap
ruckus_fastiron
ruijie_os
silverpeak_vxoa
sixwind_os
sophos_sfos
supermicro_smis
telcosystems_binos
teldat_cit
tplink_jetstream
ubiquiti_edge
ubiquiti_edgerouter
ubiquiti_edgeswitch
ubiquiti_unifiswitch
vertiv_mph
vyatta_vyos
vyos
watchguard_fireware
yamaha
zte_zxros
zyxel_os

2025-07-19 00:09:19,591 - nornir.core.task -    ERROR -      start() - Host 'leaf2': task 'netmiko_send_command' failed with traceback:
Traceback (most recent call last):
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/nornir_netmiko/tasks/netmiko_send_command.py", line 26, in netmiko_send_command
    net_connect = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/nornir/core/inventory.py", line 476, in get_connection
    self.open_connection(
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/nornir/core/inventory.py", line 528, in open_connection
    conn_obj.open(
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/nornir_netmiko/connections/netmiko.py", line 59, in open
    connection = ConnectHandler(**parameters)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/netmiko/ssh_dispatcher.py", line 455, in ConnectHandler
    raise ValueError(
ValueError: Unsupported 'device_type' currently supported platforms are:
a10
accedian
adtran_os
adva_fsp150f2
adva_fsp150f3
alaxala_ax26s
alaxala_ax36s
alcatel_aos
alcatel_sros
allied_telesis_awplus
apresia_aeos
arista_eos
arris_cer
aruba_aoscx
aruba_os
aruba_osswitch
aruba_procurve
asterfusion_asternos
audiocode_66
audiocode_72
audiocode_shell
avaya_ers
avaya_vsp
bintec_boss
broadcom_icos
brocade_fastiron
brocade_fos
brocade_netiron
brocade_nos
brocade_vdx
brocade_vyos
calix_b6
casa_cmts
cdot_cros
centec_os
checkpoint_gaia
ciena_saos
ciena_saos10
ciena_waveserver
cisco_apic
cisco_asa
cisco_ftd
cisco_ios
cisco_nxos
cisco_s200
cisco_s300
cisco_tp
cisco_viptela
cisco_wlc
cisco_xe
cisco_xr
cloudgenix_ion
corelight_linux
coriant
cumulus_linux
dell_dnos9
dell_force10
dell_isilon
dell_os10
dell_os6
dell_os9
dell_powerconnect
dell_sonic
digi_transport
dlink_ds
edgecore_sonic
ekinops_ek360
eltex
eltex_esr
endace
enterasys
ericsson_ipos
ericsson_mltn63
ericsson_mltn66
extreme
extreme_ers
extreme_exos
extreme_netiron
extreme_nos
extreme_slx
extreme_tierra
extreme_vdx
extreme_vsp
extreme_wing
f5_linux
f5_ltm
f5_tmsh
fiberstore_fsos
fiberstore_fsosv2
fiberstore_networkos
flexvnf
fortinet
garderos_grs
generic
generic_termserver
h3c_comware
hillstone_stoneos
hp_comware
hp_procurve
huawei
huawei_olt
huawei_smartax
huawei_smartaxmmi
huawei_vrp
huawei_vrpv8
infinera_packet
ipinfusion_ocnos
juniper
juniper_junos
juniper_screenos
keymile
keymile_nos
lancom_lcossx4
linux
maipu
mellanox
mellanox_mlnxos
mikrotik_routeros
mikrotik_switchos
mrv_lx
mrv_optiswitch
nec_ix
netapp_cdot
netgear_prosafe
netscaler
nokia_srl
nokia_sros
oneaccess_oneos
ovs_linux
paloalto_panos
pluribus
quanta_mesh
rad_etx
raisecom_roap
ruckus_fastiron
ruijie_os
silverpeak_vxoa
sixwind_os
sophos_sfos
supermicro_smis
telcosystems_binos
teldat_cit
tplink_jetstream
ubiquiti_edge
ubiquiti_edgerouter
ubiquiti_edgeswitch
ubiquiti_unifiswitch
vertiv_mph
vyatta_vyos
vyos
watchguard_fireware
yamaha
zte_zxros
zyxel_os

2025-07-19 00:09:19,591 - nornir.core.task -    ERROR -      start() - Host 'spine1': task 'netmiko_send_command' failed with traceback:
Traceback (most recent call last):
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/nornir_netmiko/tasks/netmiko_send_command.py", line 26, in netmiko_send_command
    net_connect = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/nornir/core/inventory.py", line 476, in get_connection
    self.open_connection(
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/nornir/core/inventory.py", line 528, in open_connection
    conn_obj.open(
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/nornir_netmiko/connections/netmiko.py", line 59, in open
    connection = ConnectHandler(**parameters)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/netmiko/ssh_dispatcher.py", line 455, in ConnectHandler
    raise ValueError(
ValueError: Unsupported 'device_type' currently supported platforms are:
a10
accedian
adtran_os
adva_fsp150f2
adva_fsp150f3
alaxala_ax26s
alaxala_ax36s
alcatel_aos
alcatel_sros
allied_telesis_awplus
apresia_aeos
arista_eos
arris_cer
aruba_aoscx
aruba_os
aruba_osswitch
aruba_procurve
asterfusion_asternos
audiocode_66
audiocode_72
audiocode_shell
avaya_ers
avaya_vsp
bintec_boss
broadcom_icos
brocade_fastiron
brocade_fos
brocade_netiron
brocade_nos
brocade_vdx
brocade_vyos
calix_b6
casa_cmts
cdot_cros
centec_os
checkpoint_gaia
ciena_saos
ciena_saos10
ciena_waveserver
cisco_apic
cisco_asa
cisco_ftd
cisco_ios
cisco_nxos
cisco_s200
cisco_s300
cisco_tp
cisco_viptela
cisco_wlc
cisco_xe
cisco_xr
cloudgenix_ion
corelight_linux
coriant
cumulus_linux
dell_dnos9
dell_force10
dell_isilon
dell_os10
dell_os6
dell_os9
dell_powerconnect
dell_sonic
digi_transport
dlink_ds
edgecore_sonic
ekinops_ek360
eltex
eltex_esr
endace
enterasys
ericsson_ipos
ericsson_mltn63
ericsson_mltn66
extreme
extreme_ers
extreme_exos
extreme_netiron
extreme_nos
extreme_slx
extreme_tierra
extreme_vdx
extreme_vsp
extreme_wing
f5_linux
f5_ltm
f5_tmsh
fiberstore_fsos
fiberstore_fsosv2
fiberstore_networkos
flexvnf
fortinet
garderos_grs
generic
generic_termserver
h3c_comware
hillstone_stoneos
hp_comware
hp_procurve
huawei
huawei_olt
huawei_smartax
huawei_smartaxmmi
huawei_vrp
huawei_vrpv8
infinera_packet
ipinfusion_ocnos
juniper
juniper_junos
juniper_screenos
keymile
keymile_nos
lancom_lcossx4
linux
maipu
mellanox
mellanox_mlnxos
mikrotik_routeros
mikrotik_switchos
mrv_lx
mrv_optiswitch
nec_ix
netapp_cdot
netgear_prosafe
netscaler
nokia_srl
nokia_sros
oneaccess_oneos
ovs_linux
paloalto_panos
pluribus
quanta_mesh
rad_etx
raisecom_roap
ruckus_fastiron
ruijie_os
silverpeak_vxoa
sixwind_os
sophos_sfos
supermicro_smis
telcosystems_binos
teldat_cit
tplink_jetstream
ubiquiti_edge
ubiquiti_edgerouter
ubiquiti_edgeswitch
ubiquiti_unifiswitch
vertiv_mph
vyatta_vyos
vyos
watchguard_fireware
yamaha
zte_zxros
zyxel_os

2025-07-19 00:11:16,179 -  nornir.core -     INFO -        run() - Running task "Execute 'show ip interface brief' and parse with Genie" with args {'command_to_run': 'show ip interface brief'} on 3 hosts
2025-07-19 00:11:16,648 - nornir.core.task -    ERROR -      start() - Host 'leaf1': task 'netmiko_send_command' failed with traceback:
Traceback (most recent call last):
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/nornir_netmiko/tasks/netmiko_send_command.py", line 32, in netmiko_send_command
    result = net_connect.send_command(command_string, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/netmiko/base_connection.py", line 111, in wrapper_decorator
    return_val = func(self, *args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/netmiko/utilities.py", line 667, in wrapper_decorator
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: BaseConnection.send_command() got an unexpected keyword argument 'logging_level'

2025-07-19 00:11:16,666 - nornir.core.task -    ERROR -      start() - Host 'leaf2': task 'netmiko_send_command' failed with traceback:
Traceback (most recent call last):
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/nornir_netmiko/tasks/netmiko_send_command.py", line 32, in netmiko_send_command
    result = net_connect.send_command(command_string, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/netmiko/base_connection.py", line 111, in wrapper_decorator
    return_val = func(self, *args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/netmiko/utilities.py", line 667, in wrapper_decorator
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: BaseConnection.send_command() got an unexpected keyword argument 'logging_level'

2025-07-19 00:11:16,696 - nornir.core.task -    ERROR -      start() - Host 'spine1': task 'netmiko_send_command' failed with traceback:
Traceback (most recent call last):
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/nornir_netmiko/tasks/netmiko_send_command.py", line 32, in netmiko_send_command
    result = net_connect.send_command(command_string, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/netmiko/base_connection.py", line 111, in wrapper_decorator
    return_val = func(self, *args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/netmiko/utilities.py", line 667, in wrapper_decorator
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: BaseConnection.send_command() got an unexpected keyword argument 'logging_level'

2025-07-19 00:12:36,738 -  nornir.core -     INFO -        run() - Running task "Execute 'show ip interface brief' and parse with Genie" with args {'command_to_run': 'show ip interface brief'} on 3 hosts
2025-07-19 00:12:37,337 - nornir.core.task -    ERROR -      start() - Host 'leaf2': task 'netmiko_send_command' failed with traceback:
Traceback (most recent call last):
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/nornir_netmiko/tasks/netmiko_send_command.py", line 32, in netmiko_send_command
    result = net_connect.send_command(command_string, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/netmiko/base_connection.py", line 111, in wrapper_decorator
    return_val = func(self, *args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/netmiko/utilities.py", line 667, in wrapper_decorator
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/netmiko/base_connection.py", line 1849, in send_command
    return_val = structured_data_converter(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/netmiko/utilities.py", line 649, in structured_data_converter
    structured_output_genie = get_structured_data_genie(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/netmiko/utilities.py", line 556, in get_structured_data_genie
    raise ValueError(msg)
ValueError:
Genie and PyATS are not installed. Please PIP install both Genie and PyATS:
pip install genie
pip install pyats


2025-07-19 00:12:37,397 - nornir.core.task -    ERROR -      start() - Host 'leaf1': task 'netmiko_send_command' failed with traceback:
Traceback (most recent call last):
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/nornir_netmiko/tasks/netmiko_send_command.py", line 32, in netmiko_send_command
    result = net_connect.send_command(command_string, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/netmiko/base_connection.py", line 111, in wrapper_decorator
    return_val = func(self, *args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/netmiko/utilities.py", line 667, in wrapper_decorator
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/netmiko/base_connection.py", line 1849, in send_command
    return_val = structured_data_converter(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/netmiko/utilities.py", line 649, in structured_data_converter
    structured_output_genie = get_structured_data_genie(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/netmiko/utilities.py", line 556, in get_structured_data_genie
    raise ValueError(msg)
ValueError:
Genie and PyATS are not installed. Please PIP install both Genie and PyATS:
pip install genie
pip install pyats


2025-07-19 00:12:37,476 - nornir.core.task -    ERROR -      start() - Host 'spine1': task 'netmiko_send_command' failed with traceback:
Traceback (most recent call last):
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/nornir_netmiko/tasks/netmiko_send_command.py", line 32, in netmiko_send_command
    result = net_connect.send_command(command_string, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/netmiko/base_connection.py", line 111, in wrapper_decorator
    return_val = func(self, *args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/netmiko/utilities.py", line 667, in wrapper_decorator
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/netmiko/base_connection.py", line 1849, in send_command
    return_val = structured_data_converter(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/netmiko/utilities.py", line 649, in structured_data_converter
    structured_output_genie = get_structured_data_genie(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/netmiko/utilities.py", line 556, in get_structured_data_genie
    raise ValueError(msg)
ValueError:
Genie and PyATS are not installed. Please PIP install both Genie and PyATS:
pip install genie
pip install pyats


2025-07-19 00:17:05,496 -  nornir.core -     INFO -        run() - Running task "Execute 'show ip interface brief' and parse with Genie" with args {'command_to_run': 'show ip interface brief', 'enable_secret': ''} on 3 hosts
2025-07-19 00:17:05,996 - nornir.core.task -    ERROR -      start() - Host 'spine1': task 'netmiko_send_command' failed with traceback:
Traceback (most recent call last):
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/nornir_netmiko/tasks/netmiko_send_command.py", line 32, in netmiko_send_command
    result = net_connect.send_command(command_string, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/netmiko/base_connection.py", line 111, in wrapper_decorator
    return_val = func(self, *args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/netmiko/utilities.py", line 667, in wrapper_decorator
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: BaseConnection.send_command() got an unexpected keyword argument 'auth_method'

2025-07-19 00:17:06,065 - nornir.core.task -    ERROR -      start() - Host 'leaf1': task 'netmiko_send_command' failed with traceback:
Traceback (most recent call last):
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/nornir_netmiko/tasks/netmiko_send_command.py", line 32, in netmiko_send_command
    result = net_connect.send_command(command_string, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/netmiko/base_connection.py", line 111, in wrapper_decorator
    return_val = func(self, *args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/netmiko/utilities.py", line 667, in wrapper_decorator
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: BaseConnection.send_command() got an unexpected keyword argument 'auth_method'

2025-07-19 00:17:06,084 - nornir.core.task -    ERROR -      start() - Host 'leaf2': task 'netmiko_send_command' failed with traceback:
Traceback (most recent call last):
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/nornir_netmiko/tasks/netmiko_send_command.py", line 32, in netmiko_send_command
    result = net_connect.send_command(command_string, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/netmiko/base_connection.py", line 111, in wrapper_decorator
    return_val = func(self, *args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lab/net-chatbot/.venv/lib/python3.12/site-packages/netmiko/utilities.py", line 667, in wrapper_decorator
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: BaseConnection.send_command() got an unexpected keyword argument 'auth_method'
